# https://github.com/jenkinsci/helm-charts/blob/main/charts/jenkins/values.yaml
jenkins:
  namespaceOverride: jenkins 
  controller:
    servicePort: 80
    targetPort: 8080
    serviceType: LoadBalancer
    jenkinsUrl: http://test.com
    jenkinsAdminEmail: test@example.com
    JCasC:
      securityRealm: |-
        local:
          allowsSignup: false
          enableCaptcha: false
          users:
          - id: "admin"
            name: "Jenkins Admin"
            password: "admin"
      configScripts:
        jenkins-casc-configs: |
          credentials:
            system:
              domainCredentials:
              - credentials:
                domain:
                  name: "test"
                  description: "test 배포/운영용 시크릿"
          jenkins:
            globalNodeProperties:
            - envVars:
                env:
                - key: "GITHUB_TOKEN"
    installPlugins:
      - kubernetes:1.31.2
      - workflow-aggregator:2.6
      - git:4.9.0
      - configuration-as-code:1.55
      - pipeline-githubnotify-step:1.0.5
      - timestamper:1.13
      - github-pullrequest:0.3.0
      - robot:3.0.1
      - sonar:2.14
      - cvs:2.19
      - maven-plugin:3.16
      - pipeline-model-definition:1.9.3
      - subversion:2.15.2
      - email-ext:2.86
      - pollscm:1.3.1

  agent:
    yamlTemplate: |- 
      apiVersion: v1
      kind: Pod
      spec:
        containers:
        - name: shell
          image: ubuntu
          command:
            - sleep
          args:
          - infinity